

site_name: Guia Bolso
site_description: Repositório da disciplina de Requisitos 2019.1
repo_url: https://github.com/rafaelmakaha/2019.1-Guia-Bolso
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://fga-disciplinas.github.io/2019.1-Guia-Bolso/">Requisitos 2019.1</a>.
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'favicon.png'
  favicon: 'favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/fga-disciplinas/2019.1-Guia-Bolso'
extra_css:
  - 'stylesheets/extra.css'
plugins:
  - search
pages:
  - Home: 'index.md'
  - Pré rastreabilidade:
    - Richpicture: 'pre-rastreabilidade/richpicture.md'
    - Argumentação: 'pre-rastreabilidade/argumentacao.md'
  - Elicitação de requisitos:
    - Prototipação: 'elicitacao-de-requisitos/prototipacao.md'
    - Análise de protocolo: 'elicitacao-de-requisitos/analise-de-protocolo.md'
    - Questionário: 'elicitacao-de-requisitos/questionario.md'
    - Brainstorm: 'elicitacao-de-requisitos/brainstorm.md'
    - Instrospecção: 'elicitacao-de-requisitos/introspeccao.md'
    - Entrevista: 'elicitacao-de-requisitos/entrevista.md'
    - Storytelling: 'elicitacao-de-requisitos/storytelling.md'
  - Modelagem:
    - Léxicos: 'modelagem/lexicos.md'
    - Cenários: 'modelagem/cenarios.md'
  - Histórico:
    - Introspecção-v1: 'historico/introspeccao-v1.md'
  